# best_agent_mario_2L.yaml
defaults:
  - _self_

agent:
  info:
    mode: "train_raa"        # Mode of the agent
    type: "DQN RAA"              # Type of agent
    dev_mode: false
    abs_path: true
    state_space: [6, 84, 84]
    action_space: 5
    conv_layers: 2
  train_params:
    teacher_config:
        batch_size: 32
        lr: 0.0005
        gamma: 0.90
        target_update: 500
        max_memory_size: 4000
        dropout: 0.
        exploration:
          max_rate: 1.0
          min_rate: 0.02
          decay: 0.999
    student_config:
        batch_size: 32
        lr: 0.0005
        gamma: 0.90
        target_update: 500
        max_memory_size: 4000
        dropout: 0.
        exploration:
          max_rate: 1.0
          min_rate: 0.02
          decay: 0.999
    